export const DATA = [
    {
        id: '1',
        slug: 'what-are-anxiety-depression',
        title: 'What are anxiety and depression?',
        subtitle: 'Understanding the basics of these common conditions.',
        sections: [
            { id: '1', slug: 'introduction', title: 'Introduction', hasRead: false },
            { id: '2', slug: 'what-is-anxiety', title: 'What is anxiety?', hasRead: false },
            { id: '3', slug: 'what-is-depression', title: 'What is depression?', hasRead: false },
            { id: '4', slug: 'anxiety-depression-together', title: 'Anxiety and depression together', hasRead: false },
            { id: '5', slug: 'what-causes-them', title: 'What causes them?', hasRead: false },
            { id: '6', slug: 'goals-of-care', title: 'Goals of care', hasRead: false },
        ],
    },
    {
        id: '2',
        slug: 'symptoms-self-checks',
        title: 'Symptoms and self checks',
        subtitle: 'Recognizing signs and monitoring your progress.',
        sections: [
            { id: '1', slug: 'introduction', title: 'Introduction', hasRead: false },
            { id: '2', slug: 'common-symptoms-anxiety', title: 'Common symptoms of anxiety', hasRead: false },
            { id: '3', slug: 'common-symptoms-depression', title: 'Common symptoms of depression', hasRead: false },
            { id: '4', slug: 'panic-attacks', title: 'Panic attacks', hasRead: false },
            { id: '5', slug: 'sleep-energy-concentration', title: 'Sleep, energy, and concentration', hasRead: false },
            { id: '6', slug: 'self-check-questionnaires', title: 'Self check questionnaires and what scores mean', hasRead: false },
        ],
    },
    {
        id: '3',
        slug: 'when-to-get-help',
        title: 'When to get help and what to do in a crisis',
        subtitle: 'Knowing when to reach out and how to stay safe.',
        sections: [
            { id: '1', slug: 'introduction', title: 'Introduction', hasRead: false },
            { id: '2', slug: 'when-to-talk-clinician', title: 'When to talk with a clinician', hasRead: false },
            { id: '3', slug: 'warning-signs', title: 'Warning signs that need urgent help', hasRead: false },
            { id: '4', slug: 'thinking-about-self-harm', title: 'If you are thinking about self-harm', hasRead: false },
            { id: '5', slug: 'supporting-loved-one', title: 'How to support a loved one', hasRead: false },
            { id: '6', slug: 'urgent-evaluation', title: 'What to expect in an urgent evaluation', hasRead: false },
        ],
    },
    {
        id: '4',
        slug: 'therapy-options',
        title: 'Therapy options',
        subtitle: 'Exploring different types of therapy and how they help.',
        sections: [
            { id: '1', slug: 'introduction', title: 'Introduction', hasRead: false },
            { id: '2', slug: 'what-is-therapy', title: 'What therapy is and how it helps', hasRead: false },
            { id: '3', slug: 'cbt-act-types', title: 'CBT, ACT, and other common types', hasRead: false },
            { id: '4', slug: 'therapy-duration', title: 'How long therapy takes and what improvement looks like', hasRead: false },
            { id: '5', slug: 'finding-affording-care', title: 'Finding a therapist and affording care', hasRead: false },
            { id: '6', slug: 'therapy-not-working', title: 'What to do if therapy is not working', hasRead: false },
        ],
    },
    {
        id: '5',
        slug: 'medicines',
        title: 'Medicines for depression and anxiety',
        subtitle: 'Understanding medication options and how they work.',
        sections: [
            { id: '1', slug: 'introduction', title: 'Introduction', hasRead: false },
            { id: '2', slug: 'how-antidepressants-work', title: 'How antidepressants work in plain language', hasRead: false },
            { id: '3', slug: 'ssris-snris', title: 'SSRIs and SNRIs', hasRead: false },
            { id: '4', slug: 'other-options', title: 'Other options and when they are used', hasRead: false },
            { id: '5', slug: 'side-effects', title: 'Side effects, what is common, and what is serious', hasRead: false },
            { id: '6', slug: 'starting-switching-stopping', title: 'Starting, switching, and stopping medicines safely', hasRead: false },
        ],
    },
    {
        id: '6',
        slug: 'shared-decision-making',
        title: 'Shared decision making for meds',
        subtitle: 'Making informed choices about your treatment plan.',
        sections: [
            { id: '1', slug: 'introduction', title: 'Introduction', hasRead: false },
            { id: '2', slug: 'who-benefits-most', title: 'Who benefits most from medication', hasRead: false },
            { id: '3', slug: 'choosing-treatment', title: 'How to choose between therapy, meds, exercise, or combinations', hasRead: false },
            { id: '4', slug: 'week-by-week', title: 'What to expect week by week after starting medication', hasRead: false },
            { id: '5', slug: 'adjusting-treatment', title: 'When to increase the dose, switch, or add another treatment', hasRead: false },
            { id: '6', slug: 'duration-tapering', title: 'How long to stay on medication and how tapering works', hasRead: false },
        ],
    },
    {
        id: '7',
        slug: 'exercise-movement',
        title: 'Exercise and movement',
        subtitle: 'Using physical activity to support your mental health.',
        sections: [
            { id: '1', slug: 'introduction', title: 'Introduction', hasRead: false },
            { id: '2', slug: 'exercise-types', title: 'Which kinds of exercise help most for depression', hasRead: false },
            { id: '3', slug: 'how-much-exercise', title: 'How much exercise is enough to help mood', hasRead: false },
            { id: '4', slug: 'starting-unmotivated', title: 'How to start when you feel tired or unmotivated', hasRead: false },
            { id: '5', slug: 'safety-tips', title: 'Safety tips and when to talk with your doctor first', hasRead: false },
            { id: '6', slug: 'tracking-progress', title: 'Tracking progress and staying consistent', hasRead: false },
        ],
    },
    {
        id: '8',
        slug: 'daily-skills',
        title: 'Skills that help day to day',
        subtitle: 'Practical tools for managing symptoms in daily life.',
        sections: [
            { id: '1', slug: 'introduction', title: 'Introduction', hasRead: false },
            { id: '2', slug: 'breathing-grounding', title: 'Breathing and grounding skills', hasRead: false },
            { id: '3', slug: 'worry-management', title: 'Worry management and thought reframing', hasRead: false },
            { id: '4', slug: 'behavioral-activation', title: 'Behavioral activation for depression', hasRead: false },
            { id: '5', slug: 'sleep-routines', title: 'Sleep routines and light exposure', hasRead: false },
            { id: '6', slug: 'substances-mood', title: 'Alcohol, cannabis, caffeine, and mood', hasRead: false },
        ],
    },
    {
        id: '9',
        slug: 'working-with-care-team',
        title: 'Working with your care team',
        subtitle: 'Collaborating effectively with your healthcare providers.',
        sections: [
            { id: '1', slug: 'introduction', title: 'Introduction', hasRead: false },
            { id: '2', slug: 'diagnosis', title: 'How clinicians diagnose anxiety and depression', hasRead: false },
            { id: '3', slug: 'follow-up-care', title: 'Follow-up schedules and measurement-based care', hasRead: false },
            { id: '4', slug: 'tracking-symptoms', title: 'How to track symptoms and triggers', hasRead: false },
            { id: '5', slug: 'talking-about-medicines', title: 'How to talk about medicines and stopping safely', hasRead: false },
            { id: '6', slug: 'staying-well', title: 'Staying well and preventing relapse', hasRead: false },
        ],
    },
];

export const LAST_SECTION_ID = '9';
